spring:
  application:
    name: tlias-web-manament
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  servlet:
    multipart:
      #最大单个文件
      max-file-size: 10MB
      #最大请求大小(包含所有文件和表单数据)
      max-request-size: 100MB

#mybatis的配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #关键配置：自动转换下划线到驼峰
#  mapper-locations: classpath:mapper/*.xml

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-web-ai-114514
    region: cn-beijing














